### ISSUE TITLE
Jest test accidentally loaded on Travis 

### ISSUE THREAD

**Issue by tpreusse** [orbiting/backends#246]
## Bug Report

Booting the backend on travis fails:
https://travis-ci.com/orbiting/republik-tests/jobs/195254711#L3125

```
/home/travis/build/orbiting/republik-tests/apps/backends/packages/utils/ensureStringLength.jest.js:3
describe('ensureStringLength', () => {
^
ReferenceError: describe is not defined
    at Object.<anonymous> (/home/travis/build/orbiting/republik-tests/apps/backends/packages/utils/ensureStringLength.jest.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at proxy (/home/travis/build/orbiting/republik-tests/apps/backends/node_modules/lazy-cache/index.js:26:21)
    at module.exports (/home/travis/build/orbiting/republik-tests/apps/backends/node_modules/export-files/index.js:29:39)
    at Object.<anonymous> (/home/travis/build/orbiting/republik-tests/apps/backends/packages/utils/index.js:1:103)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

This happens because
1. `export-files` is used for `packages/utils` which contains a jest file `ensureStringLength.jest.js` adding a lazy `ensureStringLengthJest` export to the `utils` package
2. `export-files` uses `lazy-cache` and `lazy-cache` has a explicit condition not to be lazy on travis

```js
    // check both boolean and string in case `process.env` cases to string
    if (process.env.UNLAZY === 'true' || process.env.UNLAZY === true || process.env.TRAVIS) {
      cache[name] = fn(mod);
    }
```

**Steps to Reproduce**

- TRAVIS=1 yarn run dev

**Actual Results**

crash with `ReferenceError: describe is not defined`

**Expected Results**

run without an issue

**Possible Solutions**

- get ride of `export-files`, jest files should not even be available behind a lazy getter

**Workaround**

Set travis env to an empty string on travis:
```
TRAVIS= PORT=5000 SERVER=republik yarn start 
```

**Comment by patte** [comment]
export-files has been remove in https://github.com/orbiting/backends/pull/224
